# <font color=green> PYTHON PARA DATA SCIENCE - PANDAS
---

# <font color=green> 1. INTRODUÇÃO AO PYTHON
---

# 1.1 Introdução

> Python é uma linguagem de programação de alto nível com suporte a múltiplos paradigmas de programação. É um projeto *open source* e desde seu surgimento, em 1991, vem se tornando uma das linguagens de programação interpretadas mais populares. 
>
> Nos últimos anos Python desenvolveu uma comunidade ativa de processamento científico e análise de dados e vem se destacando como uma das linguagens mais relevantes quando o assundo é ciência de dados e machine learning, tanto no ambiente acadêmico como também no mercado.

# 1.2 Instalação e ambiente de desenvolvimento

### Instalação Local

### https://www.python.org/downloads/
### ou
### https://www.anaconda.com/distribution/

### Google Colaboratory

### https://colab.research.google.com

### Verificando versão

In [10]:
!python -V

Python 3.7.13

# 1.3 Trabalhando com dados

In [11]:
import pandas as pd
# pd.set_option('display.max_rows', 1000)
# pd.set_option('display.max_columns', 1000)

In [12]:
dataset = pd.read_csv('db.csv', sep = ';')

In [13]:
dataset

,Nome,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
0,Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64
1,Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
2,Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16
3,DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07
4,Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10
...,...,...,...,...,...,...,...
253,Phantom 2013,Motor V8,2014,27505.0,False,"['Controle de estabilidade', 'Piloto automátic...",51759.58
254,Cadillac Ciel concept,Motor V8,1991,29981.0,False,"['Bancos de couro', 'Painel digital', 'Sensor ...",51667.06
255,Classe GLK,Motor 5.0 V8 Bi-Turbo,2002,52637.0,False,"['Rodas de liga', 'Controle de tração', 'Câmbi...",68934.03
256,Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Ar condicionado', '4 X 4', 'Câmbio automátic...",122110.90
257,Macan,Motor Diesel V6,1992,50188.0,False,"['Central multimídia', 'Teto panorâmico', 'Vid...",90381.47

In [14]:
dataset.dtypes  # object é str no pandas

Nome              object
Motor             object
Ano                int64
Quilometragem    float64
Zero_km             bool
Acessórios        object
Valor            float64
dtype: object

In [15]:
dataset[['Quilometragem', 'Valor']].describe()

       Quilometragem          Valor
count     197.000000     258.000000
mean    58278.421320   98960.513101
std     35836.733259   29811.932305
min       107.000000   50742.100000
25%     27505.000000   70743.512500
50%     55083.000000   97724.380000
75%     90495.000000  124633.302500
max    119945.000000  149489.920000

In [16]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 258 entries, 0 to 257
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Nome           258 non-null    object
 1   Motor          258 non-null    object
 2   Ano            258 non-null    int64
 3   Quilometragem  197 non-null    float64
 4   Zero_km        258 non-null    bool
 5   Acessórios     258 non-null    object
 6   Valor          258 non-null    float64
dtypes: bool(1), float64(2), int64(1), object(3)
memory usage: 12.5+ KB

In [17]:
dataset.describe()

               Ano  Quilometragem          Valor
count   258.000000     197.000000     258.000000
mean   2007.511628   58278.421320   98960.513101
std       9.725906   35836.733259   29811.932305
min    1990.000000     107.000000   50742.100000
25%    1999.000000   27505.000000   70743.512500
50%    2008.000000   55083.000000   97724.380000
75%    2018.000000   90495.000000  124633.302500
max    2019.000000  119945.000000  149489.920000

# <font color=green> 2. TRABALHANDO COM TUPLAS
---

# 2.1 Criando tuplas

Tuplas são sequências imutáveis que são utilizadas para armazenar coleções de itens, geralmente heterogêneos. Podem ser construídas de várias formas:
```
- Utilizando um par de parênteses: ( )
- Utilizando uma vírgula à direita: x,
- Utilizando um par de parênteses com itens separados por vírgulas: ( x, y, z )
- Utilizando: tuple() ou tuple(iterador)
```

In [18]:
()

()

In [19]:
1, 2, 3

(1, 2, 3)

In [20]:
nome = 'Passat'
valor = 153000
(nome, valor)

('Passat', 153000)

In [21]:
nomes_carros = tuple(['Jetta Variant', 'Passat', 'Crossfox', 'DS5'])
nomes_carros

('Jetta Variant', 'Passat', 'Crossfox', 'DS5')

In [22]:
type(nomes_carros)

tuple

# 2.2 Seleções em tuplas

In [23]:
nomes_carros = tuple(['Jetta Variant', 'Passat', 'Crossfox', 'DS5'])
nomes_carros

('Jetta Variant', 'Passat', 'Crossfox', 'DS5')

In [24]:
nomes_carros[0]

'Jetta Variant'

In [25]:
nomes_carros[1]

'Passat'

In [26]:
nomes_carros[-1]

'DS5'

In [27]:
nomes_carros[1:3]

('Passat', 'Crossfox')

In [28]:
nomes_carros = ('Jetta Variant', 'Passat', 'Crossfox', 'DS5', ('Fusca', 'Gol', 'C4'))
nomes_carros

('Jetta Variant', 'Passat', 'Crossfox', 'DS5', ('Fusca', 'Gol', 'C4'))

In [29]:
nomes_carros[-1]

('Fusca', 'Gol', 'C4')

In [30]:
nomes_carros[-1][1]

'Gol'

# **Exercicio**

In [31]:
carros = (
    (
        'Jetta Variant',
        'Motor 4.0 Turbo',
        2003,
        False,
        ('Rodas de liga', 'Travas elétricas', 'Piloto automático')
    ),
    (
        'Passat',
        'Motor Diesel',
        1991,
        True,
        ('Central multimídia', 'Teto panorâmico', 'Freios ABS')
    )
)

In [32]:
carros[0][3]

False

In [33]:
carros[-1][-1][-1]

'Freios ABS'

In [34]:
carros[0][-1][:2]

('Rodas de liga', 'Travas elétricas')

# 2.3 Iterando em tuplas

In [35]:
nomes_carros = ('Jetta Variant', 'Passat', 'Crossfox', 'DS5')
nomes_carros

('Jetta Variant', 'Passat', 'Crossfox', 'DS5')

In [36]:
for item in nomes_carros:
  print(item)

Jetta Variant
Passat
Crossfox
DS5

### Desempacotamento de tuplas

In [37]:
carro_1, carro_2, carro_3, carro_4 = nomes_carros

In [38]:
carro_1

'Jetta Variant'

In [39]:
carro_2

'Passat'

In [40]:
carro_3

'Crossfox'

In [41]:
carro_4

'DS5'

In [42]:
_, a, _, b = nomes_carros

In [43]:
a

'Passat'

In [44]:
b

'DS5'

In [45]:
_, c, *_ = nomes_carros

In [46]:
c

'Passat'

## *zip()*

https://docs.python.org/3.6/library/functions.html#zip

In [47]:
carros = ['Jetta Variant', 'Passat', 'Crossfox', 'DS5']
carros

['Jetta Variant', 'Passat', 'Crossfox', 'DS5']

In [48]:
valores = [88078.64, 106161.94, 72832.16, 124549.07]
valores

[88078.64, 106161.94, 72832.16, 124549.07]

In [49]:
list(zip(carros, valores))

[('Jetta Variant', 88078.64),
 ('Passat', 106161.94),
 ('Crossfox', 72832.16),
 ('DS5', 124549.07)]

In [50]:
for item in zip(carros, valores):
  print(item)

('Jetta Variant', 88078.64)
('Passat', 106161.94)
('Crossfox', 72832.16)
('DS5', 124549.07)

In [51]:
for carro, valor in zip(carros, valores):
  print(carro, valor)

Jetta Variant 88078.64
Passat 106161.94
Crossfox 72832.16
DS5 124549.07

In [52]:
for carro, valor in zip(carros, valores):
  if valor > 100000:
    print(carro)

Passat
DS5

# **Exercício:**

In [53]:
carros = (
    (
        'Jetta Variant',
        'Motor 4.0 Turbo',
        2003,
        False,
        ('Rodas de liga', 'Travas elétricas', 'Piloto automático')
    ),
    (
        'Passat',
        'Motor Diesel',
        1991,
        True,
        ('Central multimídia', 'Teto panorâmico', 'Freios ABS')
    )
)

In [54]:
for tupla in carros:
  print(tupla)

('Jetta Variant', 'Motor 4.0 Turbo', 2003, False, ('Rodas de liga', 'Travas elétricas', 'Piloto automático'))
('Passat', 'Motor Diesel', 1991, True, ('Central multimídia', 'Teto panorâmico', 'Freios ABS'))

In [55]:
for tupla in carros:
  print(tupla[-1])

('Rodas de liga', 'Travas elétricas', 'Piloto automático')
('Central multimídia', 'Teto panorâmico', 'Freios ABS')

In [56]:
for tupla in carros:
  for item in tupla:
    print(item)

Jetta Variant
Motor 4.0 Turbo
2003
False
('Rodas de liga', 'Travas elétricas', 'Piloto automático')
Passat
Motor Diesel
1991
True
('Central multimídia', 'Teto panorâmico', 'Freios ABS')

In [57]:
for tupla in carros:
  for item in tupla[-1]:
    print(item)

Rodas de liga
Travas elétricas
Piloto automático
Central multimídia
Teto panorâmico
Freios ABS

In [58]:
nomes = ['Passat', 'Crossfox', 'DS5', 'C4', 'Jetta']
kms = [15000, 12000, 32000, 8000, 50000]

In [59]:
for nome, km in zip(nomes, kms):
  if km < 20000:
    print(nome)

Passat
Crossfox
C4

# <font color=green> 3. TRABALHANDO COM DICIONÁRIOS
---

# 3.1 Criando dicionários

Listas são coleções sequenciais, isto é, os itens destas sequências estão ordenados e utilizam índices (números inteiros) para acessar os valores.

Os dicionários são coleções um pouco diferentes. São estruturas de dados que representam um tipo de mapeamento. Mapeamentos são coleções de associações entre pares de valores onde o primeiro elemento do par é conhecido como chave (*key*) e o segundo como valor (*value*).

```
dicionario = {key_1: value_1, key_2: value_2, ..., key_n: value_n}
```

https://docs.python.org/3.6/library/stdtypes.html#typesmapping

In [60]:
carros = ['Jetta Variant', 'Passat', 'Crossfox']
carros

['Jetta Variant', 'Passat', 'Crossfox']

In [61]:
valores = [88078.64, 106161.94, 72832.16]
valores

[88078.64, 106161.94, 72832.16]

In [62]:
carros.index('Passat')

1

In [63]:
valores[carros.index('Passat')]

106161.94

In [64]:
dados = {'Jetta Variant': 88078.64, 'Passat': 106161.94, 'Crossfox': 72832.16}
dados

{'Crossfox': 72832.16, 'Jetta Variant': 88078.64, 'Passat': 106161.94}

In [65]:
type(dados)

dict

### Criando dicionários com *zip()*

In [66]:
list(zip(carros, valores))

[('Jetta Variant', 88078.64), ('Passat', 106161.94), ('Crossfox', 72832.16)]

In [67]:
dados = dict(zip(carros, valores))
dados

{'Crossfox': 72832.16, 'Jetta Variant': 88078.64, 'Passat': 106161.94}

# **Exercicios:**

In [68]:
nomes = ['Passat', 'Crossfox', 'DS5', 'C4', 'Jetta']
kms = [15000, 12000, 32000, 8000, 50000]

In [69]:
dict(zip(nomes, kms))

{'C4': 8000, 'Crossfox': 12000, 'DS5': 32000, 'Jetta': 50000, 'Passat': 15000}

# 3.2 Operações com dicionários

## *dict[ key ]*

Retorna o valor correspondente à chave (*key*) no dicionário.

In [101]:
dados = {'Jetta Variant': 88078.64, 'Passat': 106161.94, 'Crossfox': 72832.16}
dados

{'Crossfox': 72832.16, 'Jetta Variant': 88078.64, 'Passat': 106161.94}

In [71]:
dados['Passat']

106161.94

## *key in dict*

Retorna **True** se a chave (*key*) for encontrada no dicionário.

In [72]:
'Passat' in dados

True

In [73]:
'Fusca' in dados

False

In [74]:
'Fusca' not in dados

True

## *len(dict)*

Retorna o número de itens do dicionário.

In [75]:
len(dados)

3

## *dict[ key ] = value*

Inclui um item ao dicionário.

In [105]:
dados['DS5'] = 124549.07

In [100]:
dados

{'Crossfox': {'ano': 2015, 'km': 35000, 'valor': 25000},
 'Passat': {'acessorios': ['Airbag', 'ABS'],
  'ano': 2012,
  'km': 50000,
  'valor': 75000}}

## *del dict[ key ]*

Remove o item de chave (*key*) do dicionário.

In [102]:
dados

{'Crossfox': 72832.16, 'Jetta Variant': 88078.64, 'Passat': 106161.94}

In [103]:
del dados['Passat']

In [80]:
dados

{'Crossfox': 72832.16, 'DS5': 124549.07, 'Jetta Variant': 88078.64}

# **Exercicios**

In [81]:
dados = {
    'Passat': {
        'ano': 2012,
        'km': 50000,
        'valor': 75000,
        'acessorios': ['Airbag', 'ABS']
    }, 
    'Crossfox': {
        'ano': 2015,
        'km': 35000,
        'valor': 25000
    }
}

Opção A:

In [82]:
'acessorios' in dados['Crossfox']

False

In [83]:
'acessorios' in dados['Passat']

True

In [84]:
dados['Crossfox']['valor']

25000

In [85]:
dados['Passat']['acessorios']

['Airbag', 'ABS']

**Opção B:**

In [86]:
'acessorios' in 'Crossfox'

False

In [87]:
'acessorios' in 'Passat'

False

In [88]:
dados['Crossfox']['valor']

25000

In [89]:
dados['Passat']['acessorios'][-1]

'ABS'

**Opção C:**

In [90]:
'acessorios' in dados['Crossfox']

False

In [91]:
'acessorios' in dados['Passat']

True

In [92]:
# dados['valor']

In [93]:
# dados['acessorios'][-1]

**Opção D:**

In [94]:
'acessorios' in dados['Crossfox']

False

In [95]:
'acessorios' in dados['Passat']

True

In [96]:
dados['Crossfox']['valor']

25000

In [97]:
dados['Passat']['acessorios'][-1]

'ABS'

# 3.3 Métodos de dicionários

## *dict.update()*

Atualiza o dicionário.

In [106]:
dados

{'Crossfox': 72832.16, 'DS5': 124549.07, 'Jetta Variant': 88078.64}

In [107]:
dados.update({'Passat' : 106161.94})

In [108]:
dados

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Jetta Variant': 88078.64,
 'Passat': 106161.94}

In [109]:
dados.update({'Passat' : 106161.95, 'Fusca': 150000})

In [110]:
dados

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Fusca': 150000,
 'Jetta Variant': 88078.64,
 'Passat': 106161.95}

## *dict.copy()*

Cria uma cópia do dicionário.

In [111]:
dadosCopy = dados.copy()

In [112]:
dadosCopy

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Fusca': 150000,
 'Jetta Variant': 88078.64,
 'Passat': 106161.95}

In [113]:
del dadosCopy['Fusca']

In [115]:
dados

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Fusca': 150000,
 'Jetta Variant': 88078.64,
 'Passat': 106161.95}

## *dict.pop(key[, default ])*

Se a chave for encontrada no dicionário, o item é removido e seu valor é retornado. Caso contrário, o valor especificado como *default* é retornado. Se o valor *default* não for fornecido e a chave não for encontrada no dicionário um erro será gerado.

In [117]:
dadosCopy

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Jetta Variant': 88078.64,
 'Passat': 106161.95}

In [118]:
dadosCopy.pop('Passat')

106161.95

In [119]:
dadosCopy

{'Crossfox': 72832.16, 'DS5': 124549.07, 'Jetta Variant': 88078.64}

In [121]:
# dadosCopy.pop('Passat')

KeyError: ignored

In [122]:
dadosCopy.pop('Passat', 'Chave não encontrada')

'Chave não encontrada'

In [123]:
dadosCopy.pop('DS5', 'Chave não encontrada')

124549.07

In [124]:
dadosCopy

{'Crossfox': 72832.16, 'Jetta Variant': 88078.64}

## *dict.clear()*

Remove todos os itens do dicionário.

In [125]:
dadosCopy.clear()

In [126]:
dadosCopy

{}

# **Exercicios:**

In [128]:
dados = {'Jetta': 88000, 'Crossfox': 72000, 'DS5': 124000}

In [129]:
dados.update({'Passat': 85000, 'Fusca': 15000})

In [130]:
dados

{'Crossfox': 72000,
 'DS5': 124000,
 'Fusca': 15000,
 'Jetta': 88000,
 'Passat': 85000}

In [132]:
dados.update(Passat = 95000, Fusca = 160000)

In [133]:
dados = {'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Fusca': 150000,
 'Jetta Variant': 88078.64,
 'Passat': 106161.95}

# 3.4 Iterando em dicionários

## *dict.keys()*

Retorna uma lista contendo as chaves (*keys*) do dicionário.

In [134]:
dados

{'Crossfox': 72832.16,
 'DS5': 124549.07,
 'Fusca': 150000,
 'Jetta Variant': 88078.64,
 'Passat': 106161.95}

In [136]:
dados.keys()

dict_keys(['Crossfox', 'DS5', 'Fusca', 'Jetta Variant', 'Passat'])

In [137]:
for key in dados.keys():
  print(dados[key])

72832.16
124549.07
150000
88078.64
106161.95

## *dict.values()*

Retorna uma lista com todos os valores (*values*) do dicionário.

In [138]:
dados.values()

dict_values([72832.16, 124549.07, 150000, 88078.64, 106161.95])

## *dict.items()*

Retorna uma lista contendo uma tupla para cada par chave-valor (*key-value*) do dicionário.

In [139]:
dados.items()

dict_items([('Crossfox', 72832.16), ('DS5', 124549.07), ('Fusca', 150000), ('Jetta Variant', 88078.64), ('Passat', 106161.95)])

In [141]:
for item in dados.items():
  print(item)

('Crossfox', 72832.16)
('DS5', 124549.07)
('Fusca', 150000)
('Jetta Variant', 88078.64)
('Passat', 106161.95)

In [142]:
for key, value in dados.items():
  print(key, value)

Crossfox 72832.16
DS5 124549.07
Fusca 150000
Jetta Variant 88078.64
Passat 106161.95

In [143]:
for key, value in dados.items():
  if value > 100000:
    print(key)

DS5
Fusca
Passat

# **Exercicios:**

In [144]:
dados = {
    'Crossfox': {'valor': 72000, 'ano': 2005}, 
    'DS5': {'valor': 125000, 'ano': 2015}, 
    'Fusca': {'valor': 150000, 'ano': 1976}, 
    'Jetta': {'valor': 88000, 'ano': 2010}, 
    'Passat': {'valor': 106000, 'ano': 1998}
}

In [145]:
for item in dados.items():
  if item[1]['ano'] >= 2000:
    print(item[0])

Crossfox
DS5
Jetta

In [146]:
for item in dados.values():
  if item['ano'] >= 2000:
    print(item)

{'valor': 72000, 'ano': 2005}
{'valor': 125000, 'ano': 2015}
{'valor': 88000, 'ano': 2010}

In [148]:
for item in dados.items():
  if item[1]['ano'] >= 2000:
    print(dados.keys())

dict_keys(['Crossfox', 'DS5', 'Fusca', 'Jetta', 'Passat'])
dict_keys(['Crossfox', 'DS5', 'Fusca', 'Jetta', 'Passat'])
dict_keys(['Crossfox', 'DS5', 'Fusca', 'Jetta', 'Passat'])

In [149]:
for item in dados.values():
  if item['ano'] >= 2000:
    print(dados)

{'Crossfox': {'valor': 72000, 'ano': 2005}, 'DS5': {'valor': 125000, 'ano': 2015}, 'Fusca': {'valor': 150000, 'ano': 1976}, 'Jetta': {'valor': 88000, 'ano': 2010}, 'Passat': {'valor': 106000, 'ano': 1998}}
{'Crossfox': {'valor': 72000, 'ano': 2005}, 'DS5': {'valor': 125000, 'ano': 2015}, 'Fusca': {'valor': 150000, 'ano': 1976}, 'Jetta': {'valor': 88000, 'ano': 2010}, 'Passat': {'valor': 106000, 'ano': 1998}}
{'Crossfox': {'valor': 72000, 'ano': 2005}, 'DS5': {'valor': 125000, 'ano': 2015}, 'Fusca': {'valor': 150000, 'ano': 1976}, 'Jetta': {'valor': 88000, 'ano': 2010}, 'Passat': {'valor': 106000, 'ano': 1998}}

# <font color=green> 4. FUNÇÕES E PACOTES
---
    
Funções são unidades de código reutilizáveis que realizam uma tarefa específica, podem receber alguma entrada e também podem retornar alguma resultado.

# 4.1 Built-in function

A linguagem Python possui várias funções integradas que estão sempre acessíveis. Algumas já utilizamos em nosso treinamento: type(), print(), zip(), len(), set() etc.

https://docs.python.org/3.6/library/functions.html

In [150]:
dados = {'Jetta Variant': 88078.64, 'Passat': 106161.94, 'Crossfox': 72832.16}
dados

{'Crossfox': 72832.16, 'Jetta Variant': 88078.64, 'Passat': 106161.94}

In [152]:
valores = []
for valor in dados.values():
  valores.append(valor)

valores

[88078.64, 106161.94, 72832.16]

In [153]:
soma = 0
for valor in dados.values():
  soma += valor

soma

267072.74

In [154]:
list(dados.values())

[88078.64, 106161.94, 72832.16]

In [155]:
sum(dados.values())

267072.74

In [156]:
sum(dados.values(), 1000000)

1267072.7399999998

In [157]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.

In [158]:
print?

# 4.2 Definindo funções sem e com parâmetros

### Funções sem parâmetros

#### Formato padrão

```
def <nome>():
    <instruções>
```

In [159]:
def media():
  valor = (1 + 2 + 3) / 3
  print(valor)

In [160]:
media()

2.0

### Funções com parâmetros

#### Formato padrão

```
def <nome>(<param_1>, <param_2>, ..., <param_n>):
    <instruções>
```

In [161]:
def media(num1, num2, num3):
  valor = (num1 + num2 + num3) / 3
  print(valor)

In [162]:
media(1, 2, 3)

2.0

In [163]:
media(23, 45, 67)

45.0

In [164]:
def media(lista):
  valor = sum(lista) / len(lista)
  print(valor)

In [166]:
resultado = media([23, 45, 67])

45.0

In [167]:
resultado

In [168]:
type(resultado)

NoneType

# **Exercicios:**

In [189]:
dados = {
    'Crossfox': {'km': 35000, 'ano': 2005}, 
    'DS5': {'km': 17000, 'ano': 2015}, 
    'Fusca': {'km': 130000, 'ano': 1979}, 
    'Jetta': {'km': 56000, 'ano': 2011}, 
    'Passat': {'km': 62000, 'ano': 1999}
}

In [194]:
def km_media(dataset, ano_atual):
  for item in dataset.items():
    result = item[1]['km'] / (ano_atual - item[1]['ano'])
    print(result)

In [195]:
km_media(dados, 2019)

2500.0
4250.0
3250.0
7000.0
3100.0

# 4.3 Definindo funções que retornam valores

### Funções que retornam um valor

#### Formato padrão

```
def <nome>(<param_1>, <param_2>, ..., <param_n>):
    <instruções>
    return <resultado>
```

In [203]:
def media(lista):
  valor = sum(lista) / len(lista)
  return valor, len(lista)

In [205]:
media([1, 2, 3, 4, 5, 6, 7, 8, 9])

(5.0, 9)

In [206]:
resultado, n = media([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [207]:
resultado

5.0

In [208]:
n

9

### Funções que retornam mais de um valor

#### Formato padrão

```
def <nome>(<param_1>, <param_2>, ..., <param_n>):
    <instruções>
    return (<resultado_1>, <resultado_2>, ..., <resultado_n>)
```

In [ ]:
# fiz nas celulas de logo acima

# **Exercicios:**

In [209]:
dados = {
    'Crossfox': {'km': 35000, 'ano': 2005}, 
    'DS5': {'km': 17000, 'ano': 2015}, 
    'Fusca': {'km': 130000, 'ano': 1979}, 
    'Jetta': {'km': 56000, 'ano': 2011}, 
    'Passat': {'km': 62000, 'ano': 1999}
}

In [213]:
def km_media(dataset, ano_atual):
  result = {}
  for item in dataset.items():
    media = item[1]['km'] / (ano_atual - item[1]['ano'])
    result.update({item[0]: media})
  return result

In [214]:
km_media(dados, 2019)

{'Crossfox': 2500.0,
 'DS5': 4250.0,
 'Fusca': 3250.0,
 'Jetta': 7000.0,
 'Passat': 3100.0}

In [219]:
def km_media(dataset, ano_atual):
  result = {}
  for item in dataset.items():
    media = item[1]['km'] / (ano_atual - item[1]['ano'])
    item[1].update({'km_media': media})
    result.update({item[0]: item[1]})
  return result

In [220]:
km_media(dados, 2019)

{'Crossfox': {'ano': 2005, 'km': 35000, 'km_media': 2500.0},
 'DS5': {'ano': 2015, 'km': 17000, 'km_media': 4250.0},
 'Fusca': {'ano': 1979, 'km': 130000, 'km_media': 3250.0},
 'Jetta': {'ano': 2011, 'km': 56000, 'km_media': 7000.0},
 'Passat': {'ano': 1999, 'km': 62000, 'km_media': 3100.0}}

# <font color=green> 5. PANDAS BÁSICO
---

**versão: 0.25.2**
  
Pandas é uma ferramenta de manipulação de dados de alto nível, construída com base no pacote Numpy. O pacote pandas possui estruturas de dados bastante interessantes para manipulação de dados e por isso é muito utilizado por cientistas de dados.


## Estruturas de Dados

### Series

Series são arrays unidimensionais rotulados capazes de armazenar qualquer tipo de dado. Os rótulos das linhas são chamados de **index**. A forma básica de criação de uma Series é a seguinte:


```
    s = pd.Series(dados, index = index)
```

O argumento *dados* pode ser um dicionário, uma lista, um array Numpy ou uma constante.

### DataFrames

DataFrame é uma estrutura de dados tabular bidimensional com rótulos nas linha e colunas. Como a Series, os DataFrames são capazes de armazenar qualquer tipo de dados.


```
    df = pd.DataFrame(dados, index = index, columns = columns)
```

O argumento *dados* pode ser um dicionário, uma lista, um array Numpy, uma Series e outro DataFrame.

**Documentação:** https://pandas.pydata.org/pandas-docs/version/0.25/

# 5.1 Estruturas de dados

In [221]:
import pandas as pd

### Criando uma Series a partir de uma lista

In [222]:
carros = ['Jetta Variant', 'Passat', 'Crossfox']
carros

['Jetta Variant', 'Passat', 'Crossfox']

In [223]:
pd.Series(carros)

0    Jetta Variant
1           Passat
2         Crossfox
dtype: object

### Criando um DataFrame a partir de uma lista de dicionários

In [224]:
dados = [
    {'Nome': 'Jetta Variant', 'Motor': 'Motor 4.0 Turbo', 'Ano': 2003, 'Quilometragem': 44410.0, 'Zero_km': False, 'Valor': 88078.64},
    {'Nome': 'Passat', 'Motor': 'Motor Diesel', 'Ano': 1991, 'Quilometragem': 5712.0, 'Zero_km': False, 'Valor': 106161.94},
    {'Nome': 'Crossfox', 'Motor': 'Motor Diesel V8', 'Ano': 1990, 'Quilometragem': 37123.0, 'Zero_km': False, 'Valor': 72832.16}
]

In [225]:
dataset = pd.DataFrame(dados)

In [226]:
dataset

            Nome            Motor   Ano  Quilometragem  Zero_km      Valor
0  Jetta Variant  Motor 4.0 Turbo  2003        44410.0    False   88078.64
1         Passat     Motor Diesel  1991         5712.0    False  106161.94
2       Crossfox  Motor Diesel V8  1990        37123.0    False   72832.16

In [227]:
dataset[['Nome', 'Motor', 'Ano', 'Quilometragem', 'Zero_km', 'Valor']]

            Nome            Motor   Ano  Quilometragem  Zero_km      Valor
0  Jetta Variant  Motor 4.0 Turbo  2003        44410.0    False   88078.64
1         Passat     Motor Diesel  1991         5712.0    False  106161.94
2       Crossfox  Motor Diesel V8  1990        37123.0    False   72832.16

### Criando um DataFrame a partir de um dicionário

In [230]:
dados = {
    'Nome': ['Jetta Variant', 'Passat', 'Crossfox'], 
    'Motor': ['Motor 4.0 Turbo', 'Motor Diesel', 'Motor Diesel V8'],
    'Ano': [2003, 1991, 1990],
    'Quilometragem': [44410.0, 5712.0, 37123.0],
    'Zero_km': [False, False, False],
    'Valor': [88078.64, 106161.94, 72832.16]
}

In [231]:
dataset = pd.DataFrame(dados)

In [232]:
dataset

            Nome            Motor   Ano  Quilometragem  Zero_km      Valor
0  Jetta Variant  Motor 4.0 Turbo  2003        44410.0    False   88078.64
1         Passat     Motor Diesel  1991         5712.0    False  106161.94
2       Crossfox  Motor Diesel V8  1990        37123.0    False   72832.16

### Criando um DataFrame a partir de uma arquivo externo

In [240]:
dataset = pd.read_csv('db.csv', sep=';', index_col = 0)

In [ ]:
dataset

# **Exercicio:**

In [242]:
dados = {
    'Crossfox': {'km': 35000, 'ano': 2005}, 
    'DS5': {'km': 17000, 'ano': 2015}, 
    'Fusca': {'km': 130000, 'ano': 1979}, 
    'Jetta': {'km': 56000, 'ano': 2011}, 
    'Passat': {'km': 62000, 'ano': 1999}
}

In [249]:
def km_media(dataset, ano_atual):
  result = {}
  for item in dataset.items():
    media = item[1]['km'] / (ano_atual - item[1]['ano'])
    item[1].update({'km_media': media})
    result.update({item[0]: item[1]})
  return result

In [250]:
km_media(dados, 2009)

{'Crossfox': {'ano': 2005, 'km': 35000, 'km_media': 8750.0},
 'DS5': {'ano': 2015, 'km': 17000, 'km_media': -2833.3333333333335},
 'Fusca': {'ano': 1979, 'km': 130000, 'km_media': 4333.333333333333},
 'Jetta': {'ano': 2011, 'km': 56000, 'km_media': -28000.0},
 'Passat': {'ano': 1999, 'km': 62000, 'km_media': 6200.0}}

In [253]:
import pandas as pd
carros = pd.DataFrame(km_media(dados, 2019)).T

In [254]:
carros

                km     ano  km_media
Crossfox   35000.0  2005.0    2500.0
DS5        17000.0  2015.0    4250.0
Fusca     130000.0  1979.0    3250.0
Jetta      56000.0  2011.0    7000.0
Passat     62000.0  1999.0    3100.0

# 5.2 Seleções com DataFrames

### Selecionando colunas

In [255]:
dataset = pd.read_csv('db.csv', sep=';', index_col=0)

In [256]:
dataset

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07
Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10
...,...,...,...,...,...,...
Phantom 2013,Motor V8,2014,27505.0,False,"['Controle de estabilidade', 'Piloto automátic...",51759.58
Cadillac Ciel concept,Motor V8,1991,29981.0,False,"['Bancos de couro', 'Painel digital', 'Sensor ...",51667.06
Classe GLK,Motor 5.0 V8 Bi-Turbo,2002,52637.0,False,"['Rodas de liga', 'Controle de tração', 'Câmbi...",68934.03
Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Ar condicionado', '4 X 4', 'Câmbio automátic...",122110.90
Macan,Motor Diesel V6,1992,50188.0,False,"['Central multimídia', 'Teto panorâmico', 'Vid...",90381.47

In [257]:
dataset.head()

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07
Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10

In [258]:
# selecionando colunas:

In [259]:
dataset['Valor']

Nome
Jetta Variant             88078.64
Passat                   106161.94
Crossfox                  72832.16
DS5                      124549.07
Aston Martin DB4          92612.10
                           ...
Phantom 2013              51759.58
Cadillac Ciel concept     51667.06
Classe GLK                68934.03
Aston Martin DB5         122110.90
Macan                     90381.47
Name: Valor, Length: 258, dtype: float64

In [261]:
type(dataset['Valor'])

pandas.core.series.Series

In [262]:
dataset[['Valor']]

                           Valor
Nome
Jetta Variant           88078.64
Passat                 106161.94
Crossfox                72832.16
DS5                    124549.07
Aston Martin DB4        92612.10
...                          ...
Phantom 2013            51759.58
Cadillac Ciel concept   51667.06
Classe GLK              68934.03
Aston Martin DB5       122110.90
Macan                   90381.47

[258 rows x 1 columns]

In [263]:
type(dataset[['Valor']])

pandas.core.frame.DataFrame

### Selecionando linhas - [ i : j ] 

<font color=red>**Observação:**</font> A indexação tem origem no zero e nos fatiamentos (*slices*) a linha com índice i é **incluída** e a linha com índice j **não é incluída** no resultado.

In [264]:
dataset[0:3]

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16

### Utilizando .loc para seleções

<font color=red>**Observação:**</font> Seleciona um grupo de linhas e colunas segundo os rótulos ou uma matriz booleana.

In [265]:
dataset.loc['Passat']

Motor                                                 Motor Diesel
Ano                                                           1991
Quilometragem                                               5712.0
Zero_km                                                      False
Acessórios       ['Central multimídia', 'Teto panorâmico', 'Fre...
Valor                                                    106161.94
Name: Passat, dtype: object

In [266]:
dataset.loc[['Passat', 'DS5']]

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07

In [267]:
dataset.loc[['Passat', 'DS5'], ['Motor', 'Valor']]

                  Motor      Valor
Nome
Passat     Motor Diesel  106161.94
DS5     Motor 2.4 Turbo  124549.07

In [268]:
dataset.loc[:, ['Motor', 'Valor']]

                                       Motor      Valor
Nome
Jetta Variant                Motor 4.0 Turbo   88078.64
Passat                          Motor Diesel  106161.94
Crossfox                     Motor Diesel V8   72832.16
DS5                          Motor 2.4 Turbo  124549.07
Aston Martin DB4             Motor 2.4 Turbo   92612.10
...                                      ...        ...
Phantom 2013                        Motor V8   51759.58
Cadillac Ciel concept               Motor V8   51667.06
Classe GLK             Motor 5.0 V8 Bi-Turbo   68934.03
Aston Martin DB5                Motor Diesel  122110.90
Macan                        Motor Diesel V6   90381.47

[258 rows x 2 columns]

### Utilizando .iloc para seleções

<font color=red>**Observação:**</font> Seleciona com base nos índices, ou seja, se baseia na posição das informações.

In [271]:
dataset.head()

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07
Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10

In [270]:
dataset.iloc[[1]]

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94

In [273]:
dataset.iloc[1:4]

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07

In [274]:
dataset.iloc[1:4, [0, 5, 2]]

                    Motor      Valor  Quilometragem
Nome
Passat       Motor Diesel  106161.94         5712.0
Crossfox  Motor Diesel V8   72832.16        37123.0
DS5       Motor 2.4 Turbo  124549.07            NaN

In [275]:
dataset.iloc[[1, 42, 22], [0, 5, 2]]

                               Motor      Valor  Quilometragem
Nome
Passat                  Motor Diesel  106161.94         5712.0
Optima                 Motor 1.8 16v   86641.34            NaN
Lamborghini Obvious  Motor Diesel V6  133529.84        98079.0

In [276]:
dataset.iloc[:, [0, 5, 2]]

                                       Motor      Valor  Quilometragem
Nome
Jetta Variant                Motor 4.0 Turbo   88078.64        44410.0
Passat                          Motor Diesel  106161.94         5712.0
Crossfox                     Motor Diesel V8   72832.16        37123.0
DS5                          Motor 2.4 Turbo  124549.07            NaN
Aston Martin DB4             Motor 2.4 Turbo   92612.10        25757.0
...                                      ...        ...            ...
Phantom 2013                        Motor V8   51759.58        27505.0
Cadillac Ciel concept               Motor V8   51667.06        29981.0
Classe GLK             Motor 5.0 V8 Bi-Turbo   68934.03        52637.0
Aston Martin DB5                Motor Diesel  122110.90         7685.0
Macan                        Motor Diesel V6   90381.47        50188.0

[258 rows x 3 columns]

# **Exercicios:**

In [278]:
import pandas as pd

dados = {
    'Nome': ['Jetta', 'Passat', 'Crossfox', 'DS5', 'Fusca'], 
    'Motor': ['Motor 4.0 Turbo', 'Motor Diesel', 'Motor Diesel V8', 'Motor 2.0', 'Motor 1.6'],
    'Ano': [2019, 2003, 1991, 2019, 1990],
    'Quilometragem': [0.0, 5712.0, 37123.0, 0.0, 120000.0],
    'Zero_km': [True, False, False, True, False],
    'Valor': [88000.0, 106000.0, 72000.0, 89000.0, 32000.0]
}

dataset = pd.DataFrame(dados)

In [279]:
dataset

       Nome            Motor   Ano  Quilometragem  Zero_km     Valor
0     Jetta  Motor 4.0 Turbo  2019            0.0     True   88000.0
1    Passat     Motor Diesel  2003         5712.0    False  106000.0
2  Crossfox  Motor Diesel V8  1991        37123.0    False   72000.0
3       DS5        Motor 2.0  2019            0.0     True   89000.0
4     Fusca        Motor 1.6  1990       120000.0    False   32000.0

In [280]:
dataset[['Nome', 'Ano', 'Quilometragem', 'Valor']][1:3]

       Nome   Ano  Quilometragem     Valor
1    Passat  2003         5712.0  106000.0
2  Crossfox  1991        37123.0   72000.0

In [281]:
import pandas as pd

dados = {
    'Motor': ['Motor 4.0 Turbo', 'Motor Diesel', 'Motor Diesel V8', 'Motor 2.0', 'Motor 1.6'],
    'Ano': [2019, 2003, 1991, 2019, 1990],
    'Quilometragem': [0.0, 5712.0, 37123.0, 0.0, 120000.0],
    'Zero_km': [True, False, False, True, False],
    'Valor': [88000.0, 106000.0, 72000.0, 89000.0, 32000.0]
}

dataset = pd.DataFrame(dados, index = ['Jetta', 'Passat', 'Crossfox', 'DS5', 'Fusca'])

In [282]:
dataset.head()

                    Motor   Ano  Quilometragem  Zero_km     Valor
Jetta     Motor 4.0 Turbo  2019            0.0     True   88000.0
Passat       Motor Diesel  2003         5712.0    False  106000.0
Crossfox  Motor Diesel V8  1991        37123.0    False   72000.0
DS5             Motor 2.0  2019            0.0     True   89000.0
Fusca           Motor 1.6  1990       120000.0    False   32000.0

In [285]:
dataset.iloc[[1, 3], [0, -1]]

               Motor     Valor
Passat  Motor Diesel  106000.0
DS5        Motor 2.0   89000.0

In [287]:
dataset.loc[['Passat', 'DS5'], ['Motor', 'Valor']]

               Motor     Valor
Passat  Motor Diesel  106000.0
DS5        Motor 2.0   89000.0

# 5.3 Queries com DataFrames

In [289]:
dataset = pd.read_csv('db.csv', sep=';', index_col=0)

In [292]:
dataset.head()

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07
Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10

In [293]:
dataset.Motor

Nome
Jetta Variant                  Motor 4.0 Turbo
Passat                            Motor Diesel
Crossfox                       Motor Diesel V8
DS5                            Motor 2.4 Turbo
Aston Martin DB4               Motor 2.4 Turbo
                                 ...
Phantom 2013                          Motor V8
Cadillac Ciel concept                 Motor V8
Classe GLK               Motor 5.0 V8 Bi-Turbo
Aston Martin DB5                  Motor Diesel
Macan                          Motor Diesel V6
Name: Motor, Length: 258, dtype: object

In [295]:
select = dataset.Motor == 'Motor Diesel'

In [296]:
type(select)

pandas.core.series.Series

In [297]:
dataset[select]

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
Effa Hafei Picape Baú,Motor Diesel,1991,102959.0,False,"['Controle de estabilidade', 'Painel digital',...",125684.65
Sorento,Motor Diesel,2019,NaN,True,"['Sensor de chuva', 'Câmera de estacionamento'...",81399.35
New Fiesta Hatch,Motor Diesel,2017,118895.0,False,"['Sensor de estacionamento', 'Travas elétricas...",66007.16
Kangoo Express,Motor Diesel,2007,29132.0,False,"['Bancos de couro', 'Câmbio automático', 'Pilo...",146716.91
Fit,Motor Diesel,2013,44329.0,False,"['Freios ABS', 'Câmera de estacionamento', 'Câ...",77836.23
Cielo Hatch,Motor Diesel,2019,NaN,True,"['Painel digital', 'Central multimídia', 'Câme...",145197.70
Symbol,Motor Diesel,2016,117714.0,False,"['4 X 4', 'Piloto automático', 'Sensor crepusc...",133030.60
A4 Sedan,Motor Diesel,2002,30511.0,False,"['Câmera de estacionamento', '4 X 4', 'Travas ...",96369.04
A4 Avant,Motor Diesel,2014,17357.0,False,"['Teto panorâmico', '4 X 4', 'Bancos de couro'...",138946.88
Silver Shadow,Motor Diesel,2015,99052.0,False,"['4 X 4', 'Central multimídia', 'Ar condiciona...",143568.22
Camry,Motor Diesel,2019,NaN,True,"['Travas elétricas', 'Rodas de liga', 'Sensor ...",138597.27
Clio,Motor Diesel,1990,66437.0,False,"['4 X 4', 'Câmbio automático', 'Freios ABS', '...",111130.33
Série 3 M3 Coupé,Motor Diesel,2013,19896.0,False,"['Bancos de couro', 'Sensor de chuva', 'Ar con...",69219.89
Gallardo LP 560 – 4,Motor Diesel,2000,113045.0,False,"['Freios ABS', 'Teto panorâmico', 'Central mul...",144118.91
Chana Utility,Motor Diesel,2009,52034.0,False,"['Ar condicionado', 'Sensor de estacionamento'...",132662.32
TT Roadster,Motor Diesel,1998,107392.0,False,"['Ar condicionado', 'Sensor de estacionamento'...",85311.40
Aston Martin Virage,Motor Diesel,2019,NaN,True,"['Travas elétricas', 'Controle de tração', 'Câ...",97290.18
Sandero,Motor Diesel,2015,34783.0,False,"['Piloto automático', 'Teto panorâmico', 'Câmb...",112350.61
XKR,Motor Diesel,1996,85127.0,False,"['Controle de tração', 'Ar condicionado', 'Tra...",54263.16
X5,Motor Diesel,2002,13606.0,False,"['Controle de tração', 'Piloto automático', 'T...",62041.32
Dodge Dakota,Motor Diesel,1993,71544.0,False,"['Controle de tração', 'Sensor de estacionamen...",141083.35
i30 CW,Motor Diesel,2015,8497.0,False,"['Sensor de chuva', 'Vidros elétricos', 'Contr...",73311.75
Série 7 Sedã,Motor Diesel,2019,NaN,True,"['Vidros elétricos', 'Travas elétricas', 'Roda...",67539.79
V60,Motor Diesel,2004,91840.0,False,"['Rodas de liga', 'Sensor crepuscular', 'Ar co...",114728.74
Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Ar condicionado', '4 X 4', 'Câmbio automátic...",122110.90

In [298]:
dataset[(dataset.Motor == 'Motor Diesel') & (dataset.Zero_km == True)]

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Sorento,Motor Diesel,2019,NaN,True,"['Sensor de chuva', 'Câmera de estacionamento'...",81399.35
Cielo Hatch,Motor Diesel,2019,NaN,True,"['Painel digital', 'Central multimídia', 'Câme...",145197.70
Camry,Motor Diesel,2019,NaN,True,"['Travas elétricas', 'Rodas de liga', 'Sensor ...",138597.27
Aston Martin Virage,Motor Diesel,2019,NaN,True,"['Travas elétricas', 'Controle de tração', 'Câ...",97290.18
Série 7 Sedã,Motor Diesel,2019,NaN,True,"['Vidros elétricos', 'Travas elétricas', 'Roda...",67539.79

In [299]:
(dataset.Motor == 'Motor Diesel') & (dataset.Zero_km == True)  # & é and | é or

Nome
Jetta Variant            False
Passat                   False
Crossfox                 False
DS5                      False
Aston Martin DB4         False
                         ...
Phantom 2013             False
Cadillac Ciel concept    False
Classe GLK               False
Aston Martin DB5         False
Macan                    False
Length: 258, dtype: bool

### Utilizando o método query

In [301]:
dataset.query('Motor == "Motor Diesel" and Zero_km == True')

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Sorento,Motor Diesel,2019,NaN,True,"['Sensor de chuva', 'Câmera de estacionamento'...",81399.35
Cielo Hatch,Motor Diesel,2019,NaN,True,"['Painel digital', 'Central multimídia', 'Câme...",145197.70
Camry,Motor Diesel,2019,NaN,True,"['Travas elétricas', 'Rodas de liga', 'Sensor ...",138597.27
Aston Martin Virage,Motor Diesel,2019,NaN,True,"['Travas elétricas', 'Controle de tração', 'Câ...",97290.18
Série 7 Sedã,Motor Diesel,2019,NaN,True,"['Vidros elétricos', 'Travas elétricas', 'Roda...",67539.79

# **Exercício:**

In [302]:
import pandas as pd

dados = {
    'Motor': ['Motor 4.0 Turbo', 'Motor Diesel', 'Motor Diesel V8', 'Motor Diesel', 'Motor 1.6'],
    'Ano': [2019, 2003, 1991, 2019, 1990],
    'Quilometragem': [0.0, 5712.0, 37123.0, 0.0, 120000.0],
    'Zero_km': [True, False, False, True, False],
    'Valor': [88000.0, 106000.0, 72000.0, 89000.0, 32000.0]
}

dataset = pd.DataFrame(dados, index = ['Jetta', 'Passat', 'Crossfox', 'DS5', 'Fusca'])

In [303]:
dataset.head()

                    Motor   Ano  Quilometragem  Zero_km     Valor
Jetta     Motor 4.0 Turbo  2019            0.0     True   88000.0
Passat       Motor Diesel  2003         5712.0    False  106000.0
Crossfox  Motor Diesel V8  1991        37123.0    False   72000.0
DS5          Motor Diesel  2019            0.0     True   89000.0
Fusca           Motor 1.6  1990       120000.0    False   32000.0

In [304]:
dataset.query('Motor == "Motor Diesel" or Zero_km == True')

                  Motor   Ano  Quilometragem  Zero_km     Valor
Jetta   Motor 4.0 Turbo  2019            0.0     True   88000.0
Passat     Motor Diesel  2003         5712.0    False  106000.0
DS5        Motor Diesel  2019            0.0     True   89000.0

In [305]:
dataset[(dataset.Motor == 'Motor Diesel') | (dataset.Zero_km == True)]

                  Motor   Ano  Quilometragem  Zero_km     Valor
Jetta   Motor 4.0 Turbo  2019            0.0     True   88000.0
Passat     Motor Diesel  2003         5712.0    False  106000.0
DS5        Motor Diesel  2019            0.0     True   89000.0

In [306]:
dataset.query('Motor == "Motor Diesel" | Zero_km == True')

                  Motor   Ano  Quilometragem  Zero_km     Valor
Jetta   Motor 4.0 Turbo  2019            0.0     True   88000.0
Passat     Motor Diesel  2003         5712.0    False  106000.0
DS5        Motor Diesel  2019            0.0     True   89000.0

In [ ]:
# dataset[(dataset.Motor == 'Motor Diesel') or (dataset.Zero_km == True)] ERRADA

# 5.4 Iterando com DataFrames

In [309]:
dataset = pd.read_csv('db.csv', sep=';', index_col=0)

In [310]:
dataset.head()

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
Nome,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64
Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16
DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07
Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10

In [311]:
for item in dataset:
  print(item)

Motor
Ano
Quilometragem
Zero_km
Acessórios
Valor

In [ ]:
list(dataset.iterrows())

In [317]:
for index, row in dataset.iterrows():
  if 2019 - row['Ano'] != 0:
    dataset.loc[index, 'Km_media'] = row['Quilometragem'] / (2019 - row['Ano'])
  else:
    dataset.loc[index, 'Km_media'] = 0

dataset

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor,Km_media
Nome,,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003.0,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64,2775.625000
Passat,Motor Diesel,1991.0,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94,204.000000
Crossfox,Motor Diesel V8,1990.0,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16,1280.103448
DS5,Motor 2.4 Turbo,2019.0,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07,0.000000
Aston Martin DB4,Motor 2.4 Turbo,2006.0,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10,1981.307692
...,...,...,...,...,...,...,...
Cadillac Ciel concept,Motor V8,1991.0,29981.0,False,"['Bancos de couro', 'Painel digital', 'Sensor ...",51667.06,1070.750000
Classe GLK,Motor 5.0 V8 Bi-Turbo,2002.0,52637.0,False,"['Rodas de liga', 'Controle de tração', 'Câmbi...",68934.03,3096.294118
Aston Martin DB5,Motor Diesel,1996.0,7685.0,False,"['Ar condicionado', '4 X 4', 'Câmbio automátic...",122110.90,334.130435
Macan,Motor Diesel V6,1992.0,50188.0,False,"['Central multimídia', 'Teto panorâmico', 'Vid...",90381.47,1858.814815
index,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 5.5 Tratamento de dados

In [318]:
dataset.head()

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor,Km_media
Nome,,,,,,,
Jetta Variant,Motor 4.0 Turbo,2003.0,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64,2775.625000
Passat,Motor Diesel,1991.0,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94,204.000000
Crossfox,Motor Diesel V8,1990.0,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16,1280.103448
DS5,Motor 2.4 Turbo,2019.0,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07,0.000000
Aston Martin DB4,Motor 2.4 Turbo,2006.0,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10,1981.307692

In [319]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 259 entries, Jetta Variant to index
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Motor          258 non-null    object
 1   Ano            258 non-null    float64
 2   Quilometragem  197 non-null    float64
 3   Zero_km        258 non-null    object
 4   Acessórios     258 non-null    object
 5   Valor          258 non-null    float64
 6   Km_media       258 non-null    float64
dtypes: float64(4), object(3)
memory usage: 24.3+ KB

In [320]:
dataset.Quilometragem.isna()

Nome
Jetta Variant            False
Passat                   False
Crossfox                 False
DS5                       True
Aston Martin DB4         False
                         ...
Cadillac Ciel concept    False
Classe GLK               False
Aston Martin DB5         False
Macan                    False
index                     True
Name: Quilometragem, Length: 259, dtype: bool

In [321]:
dataset[dataset.Quilometragem.isna()]

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor,Km_media
Nome,,,,,,,
DS5,Motor 2.4 Turbo,2019.0,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07,0.0
A5,Motor 4.0 Turbo,2019.0,NaN,True,"['Câmbio automático', 'Câmera de estacionament...",56445.20,0.0
J5,Motor V6,2019.0,NaN,True,"['Sensor crepuscular', 'Painel digital', 'Roda...",53183.38,0.0
A3,Motor 1.0 8v,2019.0,NaN,True,"['4 X 4', 'Piloto automático', 'Central multim...",88552.39,0.0
Série 1 M,Motor V8,2019.0,NaN,True,"['Controle de estabilidade', 'Central multimíd...",94564.40,0.0
...,...,...,...,...,...,...,...
Benni Mini,Motor V8,2019.0,NaN,True,"['Sensor crepuscular', 'Câmbio automático', 'C...",126247.84,0.0
Uno,Motor Diesel V6,2019.0,NaN,True,"['Central multimídia', 'Sensor crepuscular', '...",128852.21,0.0
Santa Fe,Motor 3.0 32v,2019.0,NaN,True,"['Travas elétricas', 'Ar condicionado', '4 X 4...",129415.33,0.0
XC60,Motor 4.0 Turbo,2019.0,NaN,True,"['Painel digital', 'Piloto automático', 'Centr...",77675.79,0.0
index,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [322]:
dataset.fillna(0, inplace=True)

In [324]:
dataset.query('Zero_km == True')

,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor,Km_media
Nome,,,,,,,
DS5,Motor 2.4 Turbo,2019.0,0.0,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07,0.0
A5,Motor 4.0 Turbo,2019.0,0.0,True,"['Câmbio automático', 'Câmera de estacionament...",56445.20,0.0
J5,Motor V6,2019.0,0.0,True,"['Sensor crepuscular', 'Painel digital', 'Roda...",53183.38,0.0
A3,Motor 1.0 8v,2019.0,0.0,True,"['4 X 4', 'Piloto automático', 'Central multim...",88552.39,0.0
Série 1 M,Motor V8,2019.0,0.0,True,"['Controle de estabilidade', 'Central multimíd...",94564.40,0.0
...,...,...,...,...,...,...,...
Lamborghini Reventón,Motor 4.0 Turbo,2019.0,0.0,True,"['Controle de tração', 'Ar condicionado', 'Cen...",67664.86,0.0
Benni Mini,Motor V8,2019.0,0.0,True,"['Sensor crepuscular', 'Câmbio automático', 'C...",126247.84,0.0
Uno,Motor Diesel V6,2019.0,0.0,True,"['Central multimídia', 'Sensor crepuscular', '...",128852.21,0.0
Santa Fe,Motor 3.0 32v,2019.0,0.0,True,"['Travas elétricas', 'Ar condicionado', '4 X 4...",129415.33,0.0
XC60,Motor 4.0 Turbo,2019.0,0.0,True,"['Painel digital', 'Piloto automático', 'Centr...",77675.79,0.0

In [325]:
dataset = pd.read_csv('db.csv', sep=';')

In [326]:
dataset

,Nome,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
0,Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64
1,Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
2,Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16
3,DS5,Motor 2.4 Turbo,2019,NaN,True,"['Travas elétricas', '4 X 4', 'Vidros elétrico...",124549.07
4,Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10
...,...,...,...,...,...,...,...
253,Phantom 2013,Motor V8,2014,27505.0,False,"['Controle de estabilidade', 'Piloto automátic...",51759.58
254,Cadillac Ciel concept,Motor V8,1991,29981.0,False,"['Bancos de couro', 'Painel digital', 'Sensor ...",51667.06
255,Classe GLK,Motor 5.0 V8 Bi-Turbo,2002,52637.0,False,"['Rodas de liga', 'Controle de tração', 'Câmbi...",68934.03
256,Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Ar condicionado', '4 X 4', 'Câmbio automátic...",122110.90
257,Macan,Motor Diesel V6,1992,50188.0,False,"['Central multimídia', 'Teto panorâmico', 'Vid...",90381.47

In [327]:
dataset.dropna(subset = ['Quilometragem'], inplace=True)

In [328]:
dataset

,Nome,Motor,Ano,Quilometragem,Zero_km,Acessórios,Valor
0,Jetta Variant,Motor 4.0 Turbo,2003,44410.0,False,"['Rodas de liga', 'Travas elétricas', 'Piloto ...",88078.64
1,Passat,Motor Diesel,1991,5712.0,False,"['Central multimídia', 'Teto panorâmico', 'Fre...",106161.94
2,Crossfox,Motor Diesel V8,1990,37123.0,False,"['Piloto automático', 'Controle de estabilidad...",72832.16
4,Aston Martin DB4,Motor 2.4 Turbo,2006,25757.0,False,"['Rodas de liga', '4 X 4', 'Central multimídia...",92612.10
5,Palio Weekend,Motor 1.8 16v,2012,10728.0,False,"['Sensor de estacionamento', 'Teto panorâmico'...",97497.73
...,...,...,...,...,...,...,...
253,Phantom 2013,Motor V8,2014,27505.0,False,"['Controle de estabilidade', 'Piloto automátic...",51759.58
254,Cadillac Ciel concept,Motor V8,1991,29981.0,False,"['Bancos de couro', 'Painel digital', 'Sensor ...",51667.06
255,Classe GLK,Motor 5.0 V8 Bi-Turbo,2002,52637.0,False,"['Rodas de liga', 'Controle de tração', 'Câmbi...",68934.03
256,Aston Martin DB5,Motor Diesel,1996,7685.0,False,"['Ar condicionado', '4 X 4', 'Câmbio automátic...",122110.90
257,Macan,Motor Diesel V6,1992,50188.0,False,"['Central multimídia', 'Teto panorâmico', 'Vid...",90381.47

In [ ]:
"""
1) isna() - Detecta valores faltantes. Retorna um DataFrame ou uma Series booleana, identificando se o registro é um NA

2) fillna() - Preenche os registros identificados com NA, utilizando um método específico

3) dropna() - Remove registros com valores identificados como NA
"""